bias: 9
max_recurse: 5
nobias:
    - 封面
    - 前言
    - 目录
toc:
    封面: 1
    前言: 6
    目录: 8
    零基础: 1
    第1讲 函数极限与连续: 48
    第2讲 数列极限: 123
    第3讲 一元函数微分学的概念: 146
    第4讲 一元函数微分学的计算: 166
    第5讲 一元函数微分学的应用（一）—— 几何应用: 186
    第6讲 一元函数微分学的应用（二）—— 中值定理、微分不等式与微分不等式: 211
    第7讲 一元函数微分学的应用（三）—— 物理应用与经济应用: 233
    第8讲 一元函数积分学的概念与性质: 242
    第9讲 一元函数积分学的计算: 277
    第10讲 一元函数积分学的应用（一）—— 几何应用: 310
    第11讲 一元函数积分学的应用（二）—— 积分不等式与积分不等式: 329
    第12讲 一元函数积分学的应用（三）—— 物理应用与经济应用: 341
    第13讲 多元函数微分学: 348
    第14讲 二重积分: 382
    第15讲 微分方程: 419
    第16讲 无穷级数（数一、数三）: 451
    第17讲 多元函数积分学的预备知识（数一）: 506
    第18讲 多元函数积分学（数一）: 530
    附录1 图像变换: 588
    附录2 常用平面图形: 591
    附录3 常用空间图形: 594
    附录4 重要公式: 597
    附录5 从指数函数到双曲函数: 600
    选学内容:
        pn: 605
        toc:
            一 数列敛散性的综合判别法: 609
            二 如何寻找原函数: 617
            三 中值定理压轴题与计算方法: 626
            四 连和式与连乘式的极限: 634
            五 反常积分敛散性的综合判别法: 638
            六 一元函数积分学的计算训练题组: 644
            七 基本图形的相关几何量大观: 726
            八 古鲁金定理及其应用（数一、数二）: 737
            九 一元函数积分学的综合题: 744
            十 k次齐次函数与欧拉碎碎念: 758
            十一 级数敛散性的综合判别法（数一、数三）: 761
            十二 求级数和函数的公式法（数一、数三）: 788
